### ISSUE TITLE
Error while trying to build "Failed to compile."

### ISSUE THREAD

**Issue by raghavchalapathy** [maximevaillancourt/trace#2]
$ npm run build

> react-box@0.1.0 build /Users/raghav/Documents/ethereum/trace
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

static/js/main.3075bed2.js from UglifyJs
SyntaxError: Name expected [./~/ethereum-blockies-png/index.js:1,0]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-box@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-box@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raghav/.npm/_logs/2018-06-30T11_35_12_181Z-debug.log
raghav at raghavs-MBP in ~/Documents/ethereum/trace on master*

**Comment by maximevaillancourt** [comment]
Thanks for bringing this issue up. I updated the Webpack production config to add ES6 support to UglifyJS. The `npm run build` command should now work properly. Let me know if it also works on your end. :slightly_smiling_face:
