### ISSUE TITLE
Compiling issue 

### ISSUE THREAD

**Issue by bilalamjad837** [maximevaillancourt/trace#8]
compile time issues i think there is packages issue can you make a short video to rum and compile about this project.

**Comment by maximevaillancourt** [comment]
At what step of the [install process](https://github.com/maximevaillancourt/trace#installing--getting-started) are you seeing an issue?

Can you share the error message here?

**Comment by bilalamjad837** [comment]
i run the project successfully can u give me fevor when i insert the product click into save the project does not save the value could you please make a short video to run about this project and also run about features please .
bilalamjad837@gmail.com,
Whatsappp: +923363579525

**Comment by bilalamjad837** [comment]
the 5 and 6 step of the install process i seeing an issue ..
please contact me i need your help urgently..!
bilalamjad837@gmail.com,
Whatsappp: +923363579525


![2](https://user-images.githubusercontent.com/56451787/67844286-b8a20e00-faba-11e9-93fb-c0ca66b1e7c6.PNG)
![3](https://user-images.githubusercontent.com/56451787/67844288-b93aa480-faba-11e9-931b-a7c540926f8f.PNG)

**Comment by maximevaillancourt** [comment]
Closing this issue as it pertains to local environment setup. I'll reach out to you by email directly.
