### ISSUE TITLE
MetaMask  issue

### ISSUE THREAD

**Issue by bilalamjad837** [maximevaillancourt/trace#9]
the 5 and 6 step of the install process i seeing an issue ..
please contact me i need your help urgently..!
bilalamjad837@gmail.com,
Whatsappp: +923363579525

![2](https://user-images.githubusercontent.com/56451787/67885467-e6ac4000-fb04-11e9-89a3-d9add267136c.PNG)
![3](https://user-images.githubusercontent.com/56451787/67885480-ead85d80-fb04-11e9-9884-9278c5290cc0.PNG)

**Comment by maximevaillancourt** [comment]
Closing this issue as it pertains to local environment setup. I'll reach out to you by email directly.
